# Generated by go run ./scripts/homebrew-formula; do not edit.
class SbxConnect < Formula
  desc "Connect ACP editors to coding agents in Docker Sandboxes"
  homepage "https://github.com/dotjoshrc/sbx-connect"
  version "0.2.0"

  on_macos do
    on_arm do
      url "https://github.com/dotjoshrc/sbx-connect/releases/download/v0.2.0/sbx-connect_0.2.0_darwin_arm64.tar.gz"
      sha256 "935d38ce2ee302370cf4f43bc2f965ffd20498a3d2632cbcca458e2a1ba671e5"
    end
    on_intel do
      url "https://github.com/dotjoshrc/sbx-connect/releases/download/v0.2.0/sbx-connect_0.2.0_darwin_amd64.tar.gz"
      sha256 "bb094e4c810c0a04223eeb1e9aa3747d56712492abf7528563e6cd2f2e522fb7"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/dotjoshrc/sbx-connect/releases/download/v0.2.0/sbx-connect_0.2.0_linux_arm64.tar.gz"
      sha256 "a091125a84721ceb954c1a6de7a9d96e850f3840ebe157e6e8281989842698b8"
    end
    on_intel do
      url "https://github.com/dotjoshrc/sbx-connect/releases/download/v0.2.0/sbx-connect_0.2.0_linux_amd64.tar.gz"
      sha256 "d8dee6084dd8047dabbd978bc0a0b3c643c95e230beb3765cfebb016e0dcb495"
    end
  end

  def install
    bin.install "sbx-connect"
  end

  def caveats
    <<~EOS
      Install Docker Sandboxes separately and authenticate with sbx login.
      To connect Zed, run: sbx-connect install zed
    EOS
  end

  test do
    assert_match "sbx-connect #{version}", shell_output("#{bin}/sbx-connect version")
  end
end
