# Generated by go run ./scripts/homebrew-formula; do not edit.
class SbxConnect < Formula
  desc "Connect ACP editors to coding agents in Docker Sandboxes"
  homepage "https://github.com/dotjoshrc/sbx-connect"
  version "0.3.0"

  on_macos do
    on_arm do
      url "https://github.com/dotjoshrc/sbx-connect/releases/download/v0.3.0/sbx-connect_0.3.0_darwin_arm64.tar.gz"
      sha256 "4e947f73c6706544f77d267519cef5af2fd6868b3840c3a2add065245108392d"
    end
    on_intel do
      url "https://github.com/dotjoshrc/sbx-connect/releases/download/v0.3.0/sbx-connect_0.3.0_darwin_amd64.tar.gz"
      sha256 "cad69ee3d0f18eafeea2ac96fe461c122ac4963cb0d4158962a85b92b39560b5"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/dotjoshrc/sbx-connect/releases/download/v0.3.0/sbx-connect_0.3.0_linux_arm64.tar.gz"
      sha256 "1d9dc84c01870ac3a02908905cc81363e8614af070cd9210f4989ad8c9e4a340"
    end
    on_intel do
      url "https://github.com/dotjoshrc/sbx-connect/releases/download/v0.3.0/sbx-connect_0.3.0_linux_amd64.tar.gz"
      sha256 "d63efedf4d5464fb4913536979644175e3434d4d1da2ee8d766536c468d9115e"
    end
  end

  def install
    bin.install "sbx-connect"
  end

  def caveats
    <<~EOS
      Install Docker Sandboxes separately and authenticate with sbx login.
      To connect Zed, run: sbx-connect install zed
    EOS
  end

  test do
    assert_match "sbx-connect #{version}", shell_output("#{bin}/sbx-connect version")
  end
end
