# Generated by go run ./scripts/homebrew-formula; do not edit.
class SbxConnect < Formula
  desc "Connect ACP editors to coding agents in Docker Sandboxes"
  homepage "https://github.com/dotjoshrc/sbx-connect"
  version "0.1.0"

  on_macos do
    on_arm do
      url "https://github.com/dotjoshrc/sbx-connect/releases/download/v0.1.0/sbx-connect_0.1.0_darwin_arm64.tar.gz"
      sha256 "ee870ebaf881db4bf1e44ffd1d6b0d0eb8aa96e6628f54b2cff0e62713a010ba"
    end
    on_intel do
      url "https://github.com/dotjoshrc/sbx-connect/releases/download/v0.1.0/sbx-connect_0.1.0_darwin_amd64.tar.gz"
      sha256 "89808bb2400bcf67d527601d7770c2714b74ac615037255dc9ee2cade9d243b5"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/dotjoshrc/sbx-connect/releases/download/v0.1.0/sbx-connect_0.1.0_linux_arm64.tar.gz"
      sha256 "47f69c533f35365eb209815bace055ee8c46c849da402677c67f76caecdc582f"
    end
    on_intel do
      url "https://github.com/dotjoshrc/sbx-connect/releases/download/v0.1.0/sbx-connect_0.1.0_linux_amd64.tar.gz"
      sha256 "af444cf0a9264b4ef0a731e71195bd5692edf0931e3749b7f004621af08fd92b"
    end
  end

  def install
    bin.install "sbx-connect"
  end

  def caveats
    <<~EOS
      Install Docker Sandboxes separately and authenticate with sbx login.
      To connect Zed, run: sbx-connect install zed
    EOS
  end

  test do
    assert_match "sbx-connect #{version}", shell_output("#{bin}/sbx-connect version")
  end
end
